import { GetStaticProps } from "next";
import Head from "next/head";
import client from "../lib/sanity";
import { Article } from "../components/Article";
import { shopifyClient } from "../lib/shopify";
import { useEffect } from "react";

const articleQuery = `*\[_type == "article"\]{
   name,
   flavour,
   price,
   slug,
   description,
   image {
   ...asset->
   }
}`;

const homepageQuery = `*\[_type == "homepage"\][0] {
  title,
  subtitle
}`;

export const getStaticProps: GetStaticProps = async () => {
  const homepageData = await client.fetch(homepageQuery);
  const articleData = await client.fetch(articleQuery);

  const data = { homepageData, articleData };

  return {
    props: {
      data,
    },
  };
};

const Home = ({ data }: { data: any }) => {
  const { homepageData, articleData } = data;

  useEffect(() => {
    shopifyClient.product.fetchAll().then((products: any) => {
      console.log(JSON.parse(JSON.stringify(products)));
    });
  }, []);

  return (
    <>
      <Head>
        <title>{homepageData.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>{homepageData.title}</h1>
      </header>
      <main style={{ display: "flex" }}>
        {articleData?.map((article: any) => (
          <Article
            slug={article.slug}
            key={article.slug.currrent}
            name={article.name}
            flavour={article?.flavour}
            price={article.price}
            imageUrl={article.image?.url}
            description={article.description}
          />
        ))}
      </main>
    </>
  );
};

export default Home;
